### ISSUE TITLE
Support of canusb package for python3

### ISSUE THREAD

**Issue by AlessandroMelino** [spiralray/canusb#2]
Hello.

I am using the new release of ROS Noetic and it uses Python3, so canusb package is not compatible, because it is written in a previous version of python. 

So, Is going to be any support or update of the package for python3?

Thanks in advance.

Best regards.
Alessandro

**Comment by spiralray** [comment]
Hi,
I cannot already maintain this repository because I don't have CANUSB now, and in future.

However, this package is really simple!
It only contains just one rosmsg file and a short Python script.
You can easily fix the issue :)
